on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ deploy ]
    
  workflow_dispatch:

name: smoke-test

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Install-Script Auto -Force | Auto az ${{github.workflow}}
        azPSVersion: "latest"
